# Generated by Django 3.1.6 on 2021-03-26 13:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('code', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024, null=True)),
                ('endDate', models.DateField(null=True)),
                ('KBK', models.CharField(blank=True, default='None', max_length=64, null=True)),
                ('paymentYearMonth', models.DateField(null=True)),
                ('paymentSumRUR', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False)),
                ('kmPrice', models.DecimalField(decimal_places=5, max_digits=16, null=True)),
                ('contractUrl', models.URLField(max_length=5028, null=True)),
                ('documentBase', models.CharField(max_length=5029, null=True)),
                ('startDate', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('endDate', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('fz', models.SmallIntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('printFromUrl', models.URLField(max_length=500, null=True)),
                ('protocolDate', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('publishDate', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('regionCode', models.SmallIntegerField(null=True)),
                ('scanUrl', models.URLField(max_length=5034, null=True)),
                ('signDate', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.budget')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('inn', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=512, null=True)),
                ('kpp', models.IntegerField(null=True)),
                ('postalAddress', models.CharField(max_length=512, null=True)),
                ('regNum', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=94, null=True)),
                ('road_title', models.CharField(max_length=5037, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.IntegerField(null=True)),
                ('section_start', models.IntegerField(null=True)),
                ('section_end', models.IntegerField(null=True)),
                ('coordinates', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('inn', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('kpp', models.BigIntegerField(null=True)),
                ('factualAddress', models.CharField(max_length=3025, null=True)),
                ('organizationName', models.CharField(max_length=3026, null=True)),
                ('singularName', models.CharField(max_length=3027, null=True)),
                ('middleName', models.CharField(max_length=216, null=True)),
                ('lastName', models.CharField(max_length=216, null=True)),
                ('firstName', models.CharField(max_length=216, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section_Road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.road')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.section')),
            ],
        ),
        migrations.CreateModel(
            name='Section_Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.section')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='contracts',
            field=models.ManyToManyField(through='contracts.Section_Contract', to='contracts.Contract'),
        ),
        migrations.AddField(
            model_name='road',
            name='sections',
            field=models.ManyToManyField(through='contracts.Section_Road', to='contracts.Section'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sid', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=5049, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=5048, null=True)),
                ('region', models.SmallIntegerField(null=True)),
                ('signDate', models.DateField(null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Contract_Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Contract_Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.customer')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='customers',
            field=models.ManyToManyField(related_name='customer_contract_type', through='contracts.Contract_Customer', to='contracts.Customer'),
        ),
        migrations.AddField(
            model_name='contract',
            name='suppliers',
            field=models.ManyToManyField(through='contracts.Contract_Supplier', to='contracts.Supplier'),
        ),
    ]
