# Generated by Django 3.1.3 on 2021-03-14 11:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='contract_id',
            new_name='contract',
        ),
        migrations.RenameField(
            model_name='road',
            old_name='selections',
            new_name='sections',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contratUrl',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='scanUrld',
        ),
        migrations.RemoveField(
            model_name='section',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='section',
            name='mk',
        ),
        migrations.AddField(
            model_name='contract',
            name='contractUrl',
            field=models.URLField(max_length=5028, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='scanUrl',
            field=models.URLField(max_length=5034, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='km',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='KBK',
            field=models.CharField(blank=True, default='None', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='name',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='paymentSumRUR',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='paymentYearMonth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='documentBase',
            field=models.CharField(max_length=5029, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='endDate',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='fz',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='printFromUrl',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='protocolDate',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='publishDate',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='regionCode',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signDate',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='startDate',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='suppliers',
            field=models.ManyToManyField(through='contracts.Contract_Supplier', to='contracts.Supplier'),
        ),
        migrations.AlterField(
            model_name='contract_supplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.supplier'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='fullName',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='inn',
            field=models.BigIntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='kpp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postalAddress',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='regNum',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='region',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='signDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='title',
            field=models.CharField(max_length=5048, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=5049, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sid',
            field=models.BigIntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='road',
            name='road_title',
            field=models.CharField(max_length=5037, null=True),
        ),
        migrations.AlterField(
            model_name='road',
            name='type',
            field=models.CharField(max_length=94, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='coordinates',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_end',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_start',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='factualAddress',
            field=models.CharField(max_length=3025, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='firstName',
            field=models.CharField(max_length=216, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='inn',
            field=models.BigIntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='kpp',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='lastName',
            field=models.CharField(max_length=216, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='middleName',
            field=models.CharField(max_length=216, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='organizationName',
            field=models.CharField(max_length=3026, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='singularName',
            field=models.CharField(max_length=3027, null=True),
        ),
        migrations.CreateModel(
            name='Section_Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.section')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='contracts',
            field=models.ManyToManyField(through='contracts.Section_Contract', to='contracts.Contract'),
        ),
    ]
