# Generated by Django 3.1.3 on 2021-03-14 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20210314_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section_contract',
            old_name='selection',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='section_road',
            old_name='selection',
            new_name='section',
        ),
    ]
