# Generated by Django 3.1.3 on 2020-11-17 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('bot_chatid', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('bot_state', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20)])),
                ('object_score', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)])),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('comment', models.TextField(default='')),
            ],
        ),
    ]
