# Generated by Django 3.1.3 on 2020-11-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='photo',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='photo_path',
            field=models.CharField(default='file_path', max_length=512),
        ),
    ]
