# Generated by Django 3.1.2 on 2020-11-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('start_position', models.CharField(max_length=256)),
                ('end_position', models.CharField(max_length=256)),
                ('district', models.CharField(max_length=64)),
                ('justification', models.CharField(max_length=512)),
                ('program', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('roadway_area', models.FloatField(default=0.0)),
                ('footway_area', models.FloatField(default=0.0)),
                ('margin_area', models.FloatField(default=0.0)),
                ('total_area', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ItemizedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('year', models.IntegerField(unique=True)),
                ('items', models.ManyToManyField(to='itemized_lists.Item')),
            ],
        ),
    ]
