# Generated by Django 3.1.2 on 2020-11-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemized_lists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemizedlist',
            name='id',
        ),
        migrations.AlterField(
            model_name='itemizedlist',
            name='year',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
