# Generated by Django 3.1.2 on 2020-11-01 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('itemized_lists', '0002_auto_20201101_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='locations.object'),
        ),
    ]
