# Generated by Django 3.1.2 on 2020-10-31 14:10

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalcAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.FloatField(blank=True, default=0.0)),
                ('sign', models.FloatField(blank=True, default=0.0)),
                ('buffer', models.FloatField(blank=True, default=0.0)),
                ('pointer', models.FloatField(blank=True, default=0.0)),
                ('asperity', models.FloatField(blank=True, default=0.0)),
                ('tpu_area', models.FloatField(blank=True, default=0.0)),
                ('engin_qty', models.IntegerField(blank=True, default=0)),
                ('other_area', models.FloatField(blank=True, default=0.0)),
                ('total_area', models.FloatField(blank=True, default=0.0)),
                ('guiding_qty', models.IntegerField(blank=True, default=0)),
                ('margin_area', models.FloatField(blank=True, default=0.0)),
                ('station_qty', models.IntegerField(blank=True, default=0)),
                ('bicycle_area', models.FloatField(blank=True, default=0.0)),
                ('footway_area', models.FloatField(blank=True, default=0.0)),
                ('guiding_area', models.FloatField(blank=True, default=0.0)),
                ('inbound_area', models.FloatField(blank=True, default=0.0)),
                ('roadway_area', models.FloatField(blank=True, default=0.0)),
                ('station_area', models.FloatField(blank=True, default=0.0)),
                ('bar_antinoise', models.FloatField(blank=True, default=0.0)),
                ('cleaning_area', models.FloatField(blank=True, default=0.0)),
                ('bar_new_jersey', models.FloatField(blank=True, default=0.0)),
                ('bicycle_length', models.FloatField(blank=True, default=0.0)),
                ('guiding_length', models.FloatField(blank=True, default=0.0)),
                ('gutters_length', models.FloatField(blank=True, default=0.0)),
                ('station_number', models.IntegerField(blank=True, default=0)),
                ('traff_light_qty', models.IntegerField(blank=True, default=0)),
                ('auto_footway_area', models.FloatField(blank=True, default=0.0)),
                ('traffic_signs_qty', models.IntegerField(blank=True, default=0)),
                ('tram_rails_length', models.FloatField(blank=True, default=0.0)),
                ('bound_stone_length', models.FloatField(blank=True, default=0.0)),
                ('manual_footway_area', models.FloatField(blank=True, default=0.0)),
                ('cleaning_guiding_qty', models.IntegerField(blank=True, default=0)),
                ('cleaning_guiding_length', models.FloatField(blank=True, default=0.0)),
                ('roadway_prkg_auto_clean_area', models.FloatField(blank=True, default=0.0)),
                ('roadway_noprkg_auto_clean_area', models.FloatField(blank=True, default=0.0)),
                ('roadway_prkg_manual_clean_area', models.FloatField(blank=True, default=0.0)),
                ('roadway_noprkg_manual_clean_area', models.FloatField(blank=True, default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_person_id', models.BigIntegerField()),
                ('legal_person_version_id', models.BigIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', location_field.models.plain.PlainLocationField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.ManyToManyField(to='locations.Point')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('calc_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_objects', to='locations.calcattribute')),
                ('geometry', models.ManyToManyField(to='locations.Polygon')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_objects', to='locations.ownerid')),
            ],
        ),
    ]
